apiVersion: v2
name: lightbridge-authz
description: This chart deploys the core Lightbridge authorization service, which is responsible for handling all the authorization requests. It includes an init container that generates the necessary configuration from a template and secrets, and the main container runs the authorization service itself, which exposes both a REST and a gRPC interface. This service is responsible for validating the incoming requests against the policies defined in the lightbridge-config chart and for providing the authorization decisions to the service mesh or API gateway.

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: app-template
    version: "4.4.0"
    repository: https://bjw-s-labs.github.io/helm-charts


