{{- range $name, $p := .Values.providers }}
{{ with $p }}
{{ if .enabled }}
{{ if .endpoints }}
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: {{ $name }}
  namespace: {{ include "common.names.namespace" $ }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  schema:
    {{ include "common.tplvalues.render" ( dict "value" .schema "context" $ ) | nindent 4 }}
  backendRef:
    name: {{ $name }}
    kind: Backend
    group: gateway.envoyproxy.io
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: {{ $name }}
  namespace: {{ include "common.names.namespace" $ }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  endpoints: {{ include "common.tplvalues.render" ( dict "value" .endpoints "context" $ ) | nindent 4 }}
{{ end }}
---
{{ end -}}
{{ end -}}
{{ end -}}
