{{- if .Values.clientTraffic.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: {{ include "common.names.fullname" . }}-client-traffic
  namespace: {{ include "common.names.namespace" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  {{- if .Values.clientTraffic.targetRef }}
  targetRefs:
    - group: {{ .Values.clientTraffic.targetRef.group }}
      kind: {{ .Values.clientTraffic.targetRef.kind }}
      name: {{ .Values.clientTraffic.targetRef.name }}
  {{- end }}
  {{- with .Values.clientTraffic.enableProxyProtocol }}
  enableProxyProtocol: {{ . }}
  {{- end }}
  {{- with .Values.clientTraffic.tcpKeepalive }}
  tcpKeepalive:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}