apiVersion: v2
name: lightbridge-config
description: This chart is responsible for managing the configuration of the Lightbridge authorization system, including all the necessary networking and security policies. It defines the different authorization policies, such as rate limits, access tiers, and supported models, and it also configures the connection to the different AI providers like OpenAI and Google. The templates in this chart are used to create and manage the various custom resources needed by the service mesh or API gateway to enforce the defined policies.

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: common
    version: "*"
    repository: https://charts.bitnami.com/bitnami
