apiVersion: v2
dependencies:
- name: app-template
  version: "4.3.0"
  alias: lmcache
  repository: https://bjw-s-labs.github.io/helm-charts
description: A Helm chart for deploying the lmcache application.
icon: https://techicons.dev/icons/helm/helm-icon.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: abonghoderick@gmail.com
  name: Kunga Derick Abongho
name: lmcache
sources:
- https://github.com/adorsys/ai-helm
version: 0.2.0