apiVersion: v2

name: lmcache
description: A Helm chart to deploy LMCache - a high-performance KV cache management system for LLMs.
version: 0.1.0
appVersion: "0.3.6"
type: application

keywords:
  - lmcache
  - kv-cache
  - llm
  - ml
  - ai
  - cache
