apiVersion: v2
name: lmcache
description: A Helm chart for deploying LMCache.
version: 0.1.0
appVersion: "0.3.6"
keywords:
  - lmcache
  - kv-cache
  - llm
  - ml
  - ai
  - cache
home: https://github.com/adorsys/ai-helm/tree/main/charts/lmcache
sources:
  - https://github.com/lm-cache/lm-cache
maintainers:
  - name: adorsys
    email: info@adorsys.de
icon: https://avatars.githubusercontent.com/u/162335353?s=200&v=4
dependencies:
  - name: app-template
    version: "4.3.0"
    repository: "https://bjw-s-labs.github.io/helm-charts"