tls:
  enabled: true

  domains:
    - converse-llm.camer.digital

  secretName: converse-llm-tls

  issuer:
    enabled: true
    kind: ClusterIssuer
    name: letsencrypt
    email: security@camer.digital
    environment: staging # staging | prod

  redirectToHttps: true

gatewayClass:
  enabled: true
  name: ai-gateway
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  labels: {}
  annotations: {}

gateway:
  enabled: true
  name: ai-gateway
  className: ""
  labels: {}
  annotations: {}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
  infrastructure:
    enabled: true

envoyProxy:
  enabled: true
  name: ai-gateway
  labels: {}
  annotations: {}
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        pod:
          labels: {}
          annotations: {}
          securityContext: {}
          tolerations: []
          nodeSelector: {}
          affinity: {}
        container:
          resources: {}
          securityContext: {}
          env: []
          volumeMounts: []
        volumes: []
      envoyService:
        type: LoadBalancer
        annotations: {}
  logging:
    level:
      default: info
  telemetry:
    accessLog: {}
    metrics: {}
    tracing: {}
  bootstrap: {}
  shutdown:
    drainTimeout: 30s
    minDrainDuration: 5s

clientTrafficPolicy:
  enabled: true
  name: client-buffer-limit
  labels: {}
  annotations: {}
  targetRefs: []
  connection:
    bufferLimit: 50Mi
  http: {}
  timeout: {}
  tls: {}
  path: {}
  headers: {}
  healthCheck: {}