gatewayClass:
  enabled: true
  name: ai-gateway
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  labels: {}
  annotations: {}

gateway:
  enabled: true
  name: ai-gateway
  className: ""
  labels: {}
  annotations: {}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
  infrastructure:
    enabled: true

envoyProxy:
  enabled: true
  name: ai-gateway
  labels: {}
  annotations: {}
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        pod:
          labels: {}
          annotations: {}
          securityContext: {}
          tolerations: []
          nodeSelector: {}
          affinity: {}
        container:
          resources: {}
          securityContext: {}
          env:
            - name: GRPC_USER
              value: "<your-username>"
            - name: GRPC_PASSWORD
              value: "<your-api-key>"
          volumeMounts: []
        volumes: []
      envoyService:
        type: LoadBalancer
        annotations: {}
  logging:
    level:
      default: info
  telemetry:
    accessLog: {}
    metrics: {}
    tracing:
      provider:
        name: Otel
        otel:
          endpoint: tempo-prod-10-prod-eu-west-2.grafana.net:443
          tls:
            mode: Enabled
          http:
            path: /tempo
            hostOverride: tempo-prod-10-prod-eu-west-2.grafana.net
  bootstrap: {}
  shutdown:
    drainTimeout: 30s
    minDrainDuration: 5s

clientTrafficPolicy:
  enabled: true
  name: client-buffer-limit
  labels: {}
  annotations: {}
  targetRefs: []
  connection:
    bufferLimit: 50Mi
  http: {}
  timeout: {}
  tls: {}
  path: {}
  headers: {}
  healthCheck: {}
