{{- if and (or .Values.controllers.cronjob.enabled .Values.controllers.job.enabled) .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.rbac.serviceAccountName }}{{ .Values.rbac.serviceAccountName }}{{ else }}{{ include "keycloak-backup.fullname" . }}{{ end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak-backup.labels" . | nindent 4 }}
  annotations:
    description: "Service account for Keycloak backup and restore jobs"
{{- end }}
