{{- range $backendName, $backendConfig := .Values.backends }}
{{- if not (eq $backendConfig.enabled false) }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: {{ $backendConfig.resourceName }}
spec:
  endpoints:
    - fqdn:
        hostname: {{ $backendConfig.fqdn.hostname }}
        port: {{ $backendConfig.fqdn.port }}
{{- end }}
{{- end }}
