{{- range $backendName, $backendConfig := .Values.backends }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $backendName }}-apikey
type: Opaque
stringData:
  apiKey: {{ $backendConfig.apiKeySecret }}
{{- end }}