apiVersion: v2

name: lmcache-kserve-inference
description: A Helm chart to deploy an LMCache-enabled KServe InferenceService.
version: 0.0.1
appVersion: v0.0.1
type: application

keywords:
  - lmcache
  - kserve
  - inference
  - ml
  - ai
