apiVersion: v2
name: lightbridge-authz-umbrella
description: This is an umbrella chart and acts as the main entry point for deploying the entire Lightbridge authorization system. It doesnâ€™t have any templates of its own but instead manages the deployment of the lightbridge-authz and lightbridge-config charts as its dependencies. This chart is used to define the global configurations and to enable or disable the sub-charts as needed, providing a single point of control for the entire application stack.
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: lightbridge-authz
    version: 0.1.0
    repository: "https://adorsys-gis.github.io/ai-helm/"
  - name: lightbridge-config
    version: 0.1.0
    repository: "https://adorsys-gis.github.io/ai-helm/"
    condition: lightbridge-config.enabled