apiVersion: v2
name: lightbridge-authz-umbrella
description: A Helm chart for Lightbridge Authorization Umbrella
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: lightbridge-authz
    version: 0.1.0
    repository: "https://adorsys-gis.github.io/ai-helm/"
  - name: lightbridge-config
    version: 0.1.0
    repository: "https://adorsys-gis.github.io/ai-helm/"
    condition: lightbridge-config.enabled