{{- if .Values.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  {{- with .Values.gateway.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or .Values.gateway.annotations .Values.gatewayConfig.enabled }}
  annotations:
    {{- with .Values.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.gatewayConfig.enabled }}
    aigateway.envoyproxy.io/gateway-config: {{ .Values.gatewayConfig.name }}
    {{- end }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className | default .Values.gatewayClass.name }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .hostname }}
      hostname: {{ .hostname | quote }}
      {{- end }}
      {{- if .tls }}
      tls:
        {{- toYaml .tls | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- if and .Values.gateway.infrastructure.enabled .Values.envoyProxy.enabled }}
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: {{ .Values.envoyProxy.name }}
  {{- end }}
{{- end }}
