{{- if .Values.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  {{- with .Values.gateway.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className | default .Values.gatewayClass.name }}
  listeners:
{{- toYaml .Values.gateway.listeners | nindent 4 }}
{{- include "ai-gateway.tlsListener" . | nindent 4 }}
  {{- if and .Values.gateway.infrastructure.enabled .Values.envoyProxy.enabled }}
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: {{ .Values.envoyProxy.name }}
  {{- end }}
{{- end }}