apiVersion: v2
name: cnpg-pgdump-backup
description: Automated PostgreSQL backup and restore solution for CloudNativePG clusters
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: common
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts

