{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightbridge-authz.fullname" . }}-secret
  labels:
    {{- include "lightbridge-authz.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  JWKS_URL: {{ .Values.secret.jwksUrl | quote }}
{{- end }}
