{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (printf "%s-secret" (include "lightbridge-authz.fullname" .)) }}
  labels:
    {{- include "lightbridge-authz.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  JWKS_URL: {{ .Values.secret.jwksUrl | quote }}
{{- end }}
